<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bring_up</name>
  <version>0.0.0</version>
  <description>Robot Description and Launch Package</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <!-- Thêm dependency cho controller package -->
  <exec_depend>rnea_control</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <!-- Dòng này giúp Gazebo tìm thấy mesh trong thư mục meshes -->
    <gazebo_ros gazebo_model_path="${prefix}/.." />
  </export>
</package>